### ISSUE TITLE
Have to set NVM_DIR 

### ISSUE THREAD

**Issue by nilsojes** [stephdewit/ansible-nvm#1]
I have to add:
```
  environment:
    NVM_DIR: '{{ nvm_install_path }}'
```
to the last three tasks to make them work. Otherwise `NVM_DIR` is set to `/bin` and the tasks fail due to permission errors.

Ubuntu 18.04
Ansible 2.8.0

**Comment by stephdewit** [comment]
It's strange, I already successfully ran this role on a Ubuntu target.

Are you using a Bash-compatible shell on the target server? It should work with nearly any shell except Fish, but I didn't try it myself.

`NVM_DIR` should be set by `nvm.sh` script which is called before running the last three tasks.

**Comment by nilsojes** [comment]
I'm using the default bash shell. Anyway I just set `NVM_DIR` when including the role so I could move on without touching the source. Closing this now... Thanks!
