### ISSUE TITLE
~/.profile not found

### ISSUE THREAD

**Issue by wolf128058** [stephdewit/ansible-nvm#10]
![grafik](https://user-images.githubusercontent.com/946255/234581259-dfa0e565-19f6-4167-b154-e336273af871.png)

simply touching that file before running the ansible-role helped.
so perhaps you should ensure the existence of that file before.

**Comment by stephdewit** [comment]
Hello @wolf128058 

There is a _nvm_shell_init_file_ role variable you can use to define in which file _nvm_ will be sourced.

Couldn't you set it to a path fitting your shell configuration?

See #3.
